/**
 * Manifest parsing for batch audits.
 *
 * The single-lookup CLI answers a curiosity. The actual job is an agency or a
 * platform team holding a list — the plugins across forty client sites, the
 * extensions a company recommends internally — that wants to know which entries
 * have quietly stopped being maintained. That question is asked on a schedule,
 * not once, which is why this needs to be a file and an exit code rather than
 * something you retype.
 *
 * Format is deliberately boring so it can be generated by anything:
 *
 *     # comments and blank lines are ignored
 *     wp:limit-login-attempts
 *     vsx:ms-python.python
 *     shop:judgeme
 *
 * Parsing is separated from fetching so it can be tested without a network,
 * and so a malformed line produces a precise complaint rather than a crash
 * halfway through a long run.
 */

export const PREFIXES = {
  wp: 'wordpress',
  wordpress: 'wordpress',
  vsx: 'vscode',
  vscode: 'vscode',
  shop: 'shopify',
  shopify: 'shopify',
  cr: 'chrome',
  chrome: 'chrome',
};

/**
 * Returns { entries, errors }. Never throws: a manifest with one bad line
 * should still audit the other ninety-nine, and report the bad one by number.
 */
export function parseManifest(text) {
  const entries = [];
  const errors = [];
  const seen = new Set();

  const lines = String(text ?? '').split(/\r?\n/);
  for (let i = 0; i < lines.length; i++) {
    const lineNo = i + 1;
    // Strip trailing comments, then trim. A '#' inside an id is not legal in
    // any of these marketplaces, so this is unambiguous.
    const raw = lines[i].split('#')[0].trim();
    if (!raw) continue;

    const idx = raw.indexOf(':');
    if (idx === -1) {
      errors.push({ lineNo, raw, reason: `missing marketplace prefix — expected "wp:", "vsx:", "shop:" or "cr:"` });
      continue;
    }

    const prefix = raw.slice(0, idx).trim().toLowerCase();
    const id = raw.slice(idx + 1).trim();
    const source = PREFIXES[prefix];

    if (!source) {
      errors.push({ lineNo, raw, reason: `unknown marketplace "${prefix}"` });
      continue;
    }
    if (!id) {
      errors.push({ lineNo, raw, reason: `"${prefix}:" with no id after it` });
      continue;
    }

    // Duplicates are near-certain in a hand-maintained list and are not worth
    // a network round trip each. Silently deduped; the count is reported.
    const key = `${source}:${id}`;
    if (seen.has(key)) continue;
    seen.add(key);

    entries.push({ source, prefix, id, lineNo });
  }

  return { entries, errors };
}
